### ISSUE TITLE
hyperos a14提示无法找到浏览器uid

### ISSUE THREAD

**Issue by liwenjie119** [lingeringsound/Miui_Browser_enhance#1]
小米13u更新hyperos，A14后，模块失效，手动运行service.sh提示无法找到浏览器uid

**Comment by lingeringsound** [comment]
```
timeout 10s dumpsys package com.android.browser | grep userId | uniq | tr -cd '[0-9]' | head -n 1
```

输入上面的命令，看看有没有结果。因为我手上没有hyperos，也没有Android14的设备😂。

还是说小米的hyperos把**浏览器包名**给改了？

**Comment by liwenjie119** [comment]
> ```
> timeout 10s dumpsys package com.android.browser | grep userId | uniq | tr -cd '[0-9]' | head -n 1
> ```
> 
> 输入上面的命令，看看有没有结果。因为我手上没有hyperos，也没有Android14的设备😂。
> 
> 还是说小米的hyperos把**浏览器包名**给改了？

没有输出结果。包名没变，但是userId这一项在输出没了，可能是变成uid了，dumpsys package com.android.browser是有大片输出的，如下
[1.txt](https://github.com/lingeringsound/Miui_Browser_enhance/files/13790159/1.txt)

**Comment by lingeringsound** [comment]
```
dumpsys package com.android.browser | grep -Eo 'uid=[0-9]+[0-9][[:space:]]|userId=[0-9]+[0-9][[:space:]]' | sort | uniq | tr -cd '[0-9]' | head -n 1
```

感谢，了解了，试试用这个命令看看。

**Comment by liwenjie119** [comment]
> ```
> dumpsys package com.android.browser | grep -Eo 'uid=[0-9]+[0-9][[:space:]]|userId=[0-9]+[0-9][[:space:]]' | sort | uniq | tr -cd '[0-9]' | head -n 1
> ```
> 
> 感谢，了解了，试试用这个命令看看。

这条命令是没有问题的，获取到了

**Comment by lingeringsound** [comment]
好的👌，更新到[121](https://lingeringsound.github.io/Miui_Browser_enhance/module/MIUIbrowser121.zip)版本试试看，应该解决了😂。
